# typed: false
# frozen_string_literal: true

# Generated by Tapring from catalog/tools.json.
class Branchbrief < Formula
  desc "Turn branch changes into crisp review briefings."
  homepage "https://github.com/rogerchappel/branchbrief"
  head "https://github.com/rogerchappel/branchbrief.git", branch: "main"

  depends_on "node"
  depends_on "pnpm" => :build

  def install
    system "pnpm", "install", "--frozen-lockfile"
    system "pnpm", "build"
    libexec.install "dist"
    libexec.install "package.json"
    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")
    libexec.install "node_modules" if File.directory?("node_modules")
    bin.install_symlink libexec/"dist/cli.js" => "branchbrief"
  end

  def caveats
    <<~EOS
      HEAD formula draft for source installs; release tarball and checksum will be added once published.
      Install with: brew install --HEAD rogerchappel/tap/branchbrief
    EOS
  end

  test do
    assert_match "branchbrief", shell_output("#{bin}/branchbrief --help", 2)
  end
end
