# typed: false
# frozen_string_literal: true

# Generated by Tapring from catalog/tools.json.
class Branchbrief < Formula
  desc "Turn branch changes into crisp review briefings"
  homepage "https://github.com/rogerchappel/branchbrief"
  head "https://github.com/rogerchappel/branchbrief.git", branch: "main"

  depends_on "node"

  def install
    system "npm", "ci"
    system "npm", "run", "build"
    libexec.install "dist"
    libexec.install "package.json"
    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")
    libexec.install "node_modules" if File.directory?("node_modules")
    chmod 0755, libexec/"dist/cli.js"
    bin.write_exec_script libexec/"dist/cli.js"
    mv bin/"cli.js", bin/"branchbrief"
  end

  def caveats
    <<~EOS
      HEAD formula draft for source installs; release tarball and checksum will be added once published.
      Install with: brew install --HEAD rogerchappel/tap/branchbrief
    EOS
  end

  test do
    assert_match "branchbrief", shell_output("#{bin}/branchbrief --help 2>&1")
  end
end
