# typed: false
# frozen_string_literal: true

# Generated by Tapring from catalog/tools.json.
class Envprobe < Formula
  desc "Probe local development environments before agents make assumptions"
  homepage "https://github.com/rogerchappel/envprobe"
  head "https://github.com/rogerchappel/envprobe.git", branch: "main"

  depends_on "node"

  def install
    system "npm", "ci"
    system "npm", "run", "build"
    libexec.install "src"
    libexec.install "package.json"
    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")
    libexec.install "node_modules" if File.directory?("node_modules")
    bin.install_symlink libexec/"src/cli.js" => "envprobe"
  end

  def caveats
    <<~EOS
      HEAD formula draft for source installs only.
      Install with: brew install --HEAD rogerchappel/tap/envprobe
    EOS
  end

  test do
    assert_match "envprobe", shell_output("#{bin}/envprobe --help")
  end
end
