# typed: false
# frozen_string_literal: true

# Generated by Tapring from catalog/tools.json.
class Proofdock < Formula
  desc "Collect and check proof for agent-built software releases."
  homepage "https://github.com/rogerchappel/proofdock"
  head "https://github.com/rogerchappel/proofdock.git", branch: "main"

  depends_on "node"
  depends_on "pnpm" => :build

  def install
    system "pnpm", "install", "--frozen-lockfile"
    system "pnpm", "build"
    libexec.install "dist"
    libexec.install "package.json"
    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")
    libexec.install "node_modules" if File.directory?("node_modules")
    bin.install_symlink libexec/"dist/cli.js" => "proofdock"
  end

  def caveats
    <<~EOS
      HEAD formula draft; use for source validation until versioned release assets exist.
      Install with: brew install --HEAD rogerchappel/tap/proofdock
    EOS
  end

  test do
    assert_match "proofdock", shell_output("#{bin}/proofdock --help", 2)
  end
end
