# typed: false
# frozen_string_literal: true

# Generated by Tapring from catalog/tools.json.
class Proofdock < Formula
  desc "Collect and check proof for agent-built software releases"
  homepage "https://github.com/rogerchappel/proofdock"
  head "https://github.com/rogerchappel/proofdock.git", branch: "main"

  depends_on "node"

  def install
    system "npm", "ci"
    system "npm", "run", "build"
    libexec.install "dist"
    libexec.install "package.json"
    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")
    libexec.install "node_modules" if File.directory?("node_modules")
    chmod 0755, libexec/"dist/cli.js"
    bin.write_exec_script libexec/"dist/cli.js"
    mv bin/"cli.js", bin/"proofdock"
  end

  def caveats
    <<~EOS
      HEAD formula draft; use for source validation until versioned release assets exist.
      Install with: brew install --HEAD rogerchappel/tap/proofdock
    EOS
  end

  test do
    assert_match "proofdock", shell_output("#{bin}/proofdock --help 2>&1")
  end
end
