# typed: false
# frozen_string_literal: true

# Generated by Tapring from catalog/tools.json.
class Stackforge < Formula
  desc "Agent-friendly project scaffolding for OSS apps, APIs, and CLIs"
  homepage "https://github.com/rogerchappel/stackforge"
  head "https://github.com/rogerchappel/stackforge.git", branch: "main"

  depends_on "pnpm" => :build
  depends_on "node"

  def install
    system "pnpm", "install", "--frozen-lockfile"
    system "pnpm", "build"
    libexec.install "dist"
    libexec.install "package.json"
    libexec.install "templates"
    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")
    libexec.install "node_modules" if File.directory?("node_modules")
    chmod 0755, libexec/"dist/index.js"
    bin.write_exec_script libexec/"dist/index.js"
    mv bin/"index.js", bin/"stackforge"
    bin.write_exec_script libexec/"dist/index.js"
    mv bin/"index.js", bin/"sf"
  end

  def caveats
    <<~EOS
      HEAD formula: installs from source because packaged Homebrew release artifacts are not published yet.
      Install with: brew install --HEAD rogerchappel/tap/stackforge
    EOS
  end

  test do
    assert_match "stackforge", shell_output("#{bin}/stackforge --help 2>&1")
    assert_match "stackforge", shell_output("#{bin}/sf --help 2>&1")
  end
end
