# typed: false
# frozen_string_literal: true

# Generated by Tapring from catalog/tools.json.
class Taskbrief < Formula
  desc "Parse product prompts into reviewable engineering task briefs."
  homepage "https://github.com/rogerchappel/taskbrief"
  head "https://github.com/rogerchappel/taskbrief.git", branch: "main"

  depends_on "node"
  depends_on "pnpm" => :build

  def install
    system "pnpm", "install", "--frozen-lockfile"
    system "pnpm", "build"
    libexec.install "dist"
    libexec.install "package.json"
    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")
    libexec.install "node_modules" if File.directory?("node_modules")
    bin.install_symlink libexec/"dist/cli.js" => "taskbrief"
  end

  def caveats
    <<~EOS
      HEAD formula draft for source installs while release archives are not available.
      Install with: brew install --HEAD rogerchappel/tap/taskbrief
    EOS
  end

  test do
    assert_match "taskbrief", shell_output("#{bin}/taskbrief --help", 2)
  end
end
