# typed: false
# frozen_string_literal: true

# Generated by Tapring from catalog/tools.json.
class Worktreeguard < Formula
  desc "Keep agent work inside safe isolated Git worktrees."
  homepage "https://github.com/rogerchappel/worktreeguard"
  head "https://github.com/rogerchappel/worktreeguard.git", branch: "main"

  depends_on "node"
  depends_on "pnpm" => :build

  def install
    system "pnpm", "install", "--frozen-lockfile"
    system "pnpm", "build"
    libexec.install "src"
    libexec.install "package.json"
    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")
    libexec.install "node_modules" if File.directory?("node_modules")
    bin.install_symlink libexec/"src/index.js" => "worktreeguard"
  end

  def caveats
    <<~EOS
      HEAD formula draft; no binary release is claimed.
      Install with: brew install --HEAD rogerchappel/tap/worktreeguard
    EOS
  end

  test do
    assert_match "worktreeguard", shell_output("#{bin}/worktreeguard --help", 2)
  end
end
