import { formulaClassName } from './catalog.mjs';

function rubyArray(values) {
  return values.map((value) => `"${value}"`).join(', ');
}

export function renderFormula(tool) {
  const primaryBin = tool.bin[0];
  const packageManagerDependency = tool.build.some((step) => step.startsWith('pnpm '))
    ? '  depends_on "pnpm" => :build\n'
    : '';
  const buildSteps = tool.build.map((step) => `    system ${step.split(' ').map((part) => `"${part}"`).join(', ')}`).join('\n');
  const installDirs = tool.install.map((entry) => `    libexec.install "${entry}"`).join('\n');
  const makeExecutable = `    chmod 0755, libexec/"${tool.binPath || `dist/${primaryBin}`}"`;
  const executableName = (tool.binPath || `dist/${primaryBin}`).split('/').at(-1);
  const links = tool.bin.map((name) => `    bin.write_exec_script libexec/"${tool.binPath || `dist/${primaryBin}`}\"\n    mv bin/"${executableName}", bin/"${name}"`).join('\n');
  const testCommands = tool.bin
    .map((name) => `    assert_match "${primaryBin}", shell_output("#{bin}/${name} --help 2>&1")`)
    .join('\n');

  return `# typed: false\n# frozen_string_literal: true\n\n# Generated by Tapring from catalog/tools.json.\nclass ${formulaClassName(tool.name)} < Formula\n  desc "${tool.summary}"\n  homepage "${tool.repo}"\n  head "${tool.repo}.git", branch: "main"\n\n${packageManagerDependency}  depends_on "node"\n\n  def install\n${buildSteps}\n${installDirs}\n    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")\n    libexec.install "node_modules" if File.directory?("node_modules")\n${makeExecutable}\n${links}\n  end\n\n  def caveats\n    <<~EOS\n      ${tool.caveat}\n      Install with: brew install --HEAD rogerchappel/tap/${tool.name}\n    EOS\n  end\n\n  test do\n${testCommands}\n  end\nend\n`;
}

export function supportedFormulaNames(catalog) {
  return catalog.tools.map((tool) => tool.name).sort();
}
