import { formulaClassName } from './catalog.mjs';

function rubyArray(values) {
  return values.map((value) => `"${value}"`).join(', ');
}

export function renderFormula(tool) {
  const primaryBin = tool.bin[0];
  const buildSteps = tool.build.map((step) => `    system ${step.split(' ').map((part) => `"${part}"`).join(', ')}`).join('\n');
  const installDirs = tool.install.map((entry) => `    libexec.install "${entry}"`).join('\n');
  const links = tool.bin.map((name) => `    bin.install_symlink libexec/"${tool.binPath || `dist/${primaryBin}`}" => "${name}"`).join('\n');

  return `# typed: false\n# frozen_string_literal: true\n\n# Generated by Tapring from catalog/tools.json.\nclass ${formulaClassName(tool.name)} < Formula\n  desc "${tool.summary}"\n  homepage "${tool.repo}"\n  head "${tool.repo}.git", branch: "main"\n\n  depends_on "node"\n  depends_on "pnpm" => :build\n\n  def install\n${buildSteps}\n${installDirs}\n    libexec.install "pnpm-lock.yaml" if File.exist?("pnpm-lock.yaml")\n    libexec.install "node_modules" if File.directory?("node_modules")\n${links}\n  end\n\n  def caveats\n    <<~EOS\n      ${tool.caveat}\n      Install with: brew install --HEAD rogerchappel/tap/${tool.name}\n    EOS\n  end\n\n  test do\n    assert_match "${primaryBin}", shell_output("#{bin}/${primaryBin} --help", 2)\n  end\nend\n`;
}

export function supportedFormulaNames(catalog) {
  return catalog.tools.map((tool) => tool.name).sort();
}
